name: cosmosdb
description: API client to interact with the CosmosDB SQL-API by its REST API in Dart
version: 0.0.3-prerelease
repository: https://github.com/jonasfranz/cosmosdb

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.0
  http: ^0.13.1
  universal_io: ^2.0.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8